POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Obtener catálogo de servicios
GET http://localhost:8080/api/servicios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJpYXQiOjE3ODE0NTk0NjcsImV4cCI6MTc4MTU0NTg2N30.87GqYSFZ7oFDtbkIT6vdN8kNqGe_5L-oy_BWGoBWHbE

### Crear servicio
POST http://localhost:8080/api/servicios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJpYXQiOjE3ODE0OTYwOTcsImV4cCI6MTc4MTU4MjQ5N30.y0H9UODFm3OYgajJnttviNQgPNYYoQN9m-zdEo57gO0
Content-Type: application/json

{
  "nombreServicio": "Cambio de aceite",
  "descripcionServicio": "Cambio de aceite y filtro",
  "areaServicio": "Mantenimiento",
  "precioServicio": 450,
  "duracionServicio": 30,
  "estadoServicio": "ACTIVO"
}

### Prueba
POST http://localhost:8080/api/servicios/prueba
Authorization: Bearer TU_TOKEN

### Actualizar servicio
PUT http://localhost:8080/api/servicios/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJpYXQiOjE3ODE0OTQ0MjgsImV4cCI6MTc4MTU4MDgyOH0.Shtmew9TLy8aigdPzlMPP1n4H5AYwsTYR6M_DdjCDQQ
Content-Type: application/json

{
  "nombreServicio": "Lavado Premium Plus actualizado",
  "areaServicio": "Carwash",
  "precioServicio": 20.00,
  "duracionServicio": 60,
  "estadoServicio": "INACTIVO"
}

### Eliminar servicio
DELETE http://localhost:8080/api/servicios/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbCI6IkFETUlOSVNUUkFET1IiLCJpYXQiOjE3ODE0OTU0MjUsImV4cCI6MTc4MTU4MTgyNX0.KA49cMQGtgig4NkwbfrGaGGQlbcIRP8cdeka0_qWNbE